### ISSUE TITLE
Enable Travis CI Webhook

### ISSUE THREAD

**Issue by ChristianMurphy** [Jasig/EsupTwitter#8]
Travis CI has a configuration in place.
Tests on my local machine show that the build should pass.
Travis just needs a webhook configured so it can automatically trigger builds for Pull Requests and Commits.
<https://docs.travis-ci.com/user/getting-started/>

/cc @apetro @bjagg @drewwills

**Comment by apetro** [comment]
Turned on Travis-CI for this repo, configured to only run when `.travis.yml` is present.

**Comment by ChristianMurphy** [comment]
Thanks @apetro!
